---
title: "Week 6: Data Anonymisation"
subtitle: ""
author: "<large>Charlotte Hadley</large>"
format: 
  revealjs:
    theme: "css/lecture-styles.scss"
    slide-number: "c/t"
bibliography: "../bibtex-file.bib"
csl: "../nature.csl"
cache: true
---

## Topics for today

```{r}
library(tidyverse)
library(gt)
library(readxl)
library(janitor)
```

1. Why is data anonymisation important?

1. What are specific risks of deanonymisation of health data?

1. Case studies of deanonymisation

1. Anonymity measures: k-anonymity and l-diversity

1. R packages for working with anonymouse data and sampling

-----------

## Why is data anonymisation important? {background-color="#23241F" .center .center-x}

-----------

## Data isn't always captured knowingly

Mostly during this course we've been talking about surveys or studies where data is explicitly being collected - and participants willingly submit their data.

<br>

But that's often not the case.

<br>

> Data is collected continuously about individuals without their explicit consent - and often without implicit consent.

-----------

## Data tracking across websites

XXX Tracking cookies. They bad. They identify individuals.

-----------

## Data tracking across credit cards

XXX Bad

-----------

## Data tracking during hospital visits

There's an A&E waiting time survey that's sent to folks that attend A&E.

This survey is sent without patients opting into it.

> The Section 251 of the NHS Act 2006 [@uk_government_national_2006] provides for the use of confidential patient data without consent for a specific purpose by the HRA or the Secretary of State for Health and Social Care.

This means that there are people looking at this data and deciding who to target.

Note that the NHS makes sure there's an opt out [once you've been invited]

> However, as has always been the case, patients/service users must be given the opportunity to opt-out.

-----------

> ## Data anonymisation is important because data is everywhere

We as individuals need to think about how our data is collected. how we use data in our day-to-day lives and in our careers.

XXX Whistleblowing is important

-----------

## Specific risks of deanonymisation of health data {background-color="#23241F" .center .center-x}

-----------

## Who can be at risk of deanonymisation?

:::: {.columns}

::: {.column width="48%"}

:::  {.subheading} 
Individuals 
:::

It's the dangers to individuals that we should primarily be concerned with.

<br>

There are significant risks to individual liberty, livelihood and life from deanonymisation.

:::

::: {.column width="4%"}

:::

::: {.column width="48%"}

:::  {.subheading} 
Organisations 
:::

However, organisations also suffer from deanonymisation.

<br>

- Organisations might suffer reputational damage

- Organisations might suffer legal difficulties

- XXX Fines? XXX

:::

:::: 

> Let's focus on the individual for now. The ICO provides a useful guide to managing data protection risk designed for organisations[@information_commissioners_office_anonymisation_2012]

-----------

## What is health data again?

Recall how the Data Protection Act[@uk_government_data_2018] identifies three types of health data:

- **“biometric data”** means personal data resulting from specific technical processing relating to the physical, physiological or behavioural characteristics of an individual, which allows or confirms the unique identification of that individual, such as facial images or dactyloscopic data;

- **“data concerning health”** means personal data relating to the physical or mental health of an individual, including the provision of health care services, which reveals information about his or her health status;

- **“genetic data”** means personal data relating to the inherited or acquired genetic characteristics of an individual which gives unique information about the physiology or the health of that individual and which results, in particular, from an analysis of a biological sample from the individual in question;

-----------

### Specific risks of deanonymised health data (I)

First and foremost, there is a risk of:

- Information about someone’s private life ending up in the public domain.

<br>

This in and of itself should be of concern, but more specifically

-	Individuals might suffer distress, embarrassment, or anxiety due to sensitive information being in the public domain

<br>

There is also a significant risk from sensitive information being in the public domain that:

- Individuals might suffer harassment, attack and/or injury 

- Individuals might suffer persecution

-----------

### Specific risks of deanonymised health data (II)

- Sensitive information might be sold to third-party organisations resulting in targeted advertising.

-----------

## XXX Case study XXX

Sending baby leaflets to a woman who ordered a pregnancy test?

Is that okay?!

-----------

### Specific risks of deanonymised health data (III)

- Sensitive information might be sold to third-party organisations results in a change in service options or costs

XXX Generally financial loss? XXX

XXX I need some evidence of this last one XXX

-----------

## Case studies of deanonymisation {background-color="#23241F" .center .center-x}

-----------

## Anonymity measures: k-anonymity and l-diversity {background-color="#23241F" .center .center-x}

-----------

## R packages for working with anonymouse data and sampling {background-color="#23241F" .center .center-x}

-----------

XXX DRAGONS XXXX

## USEFUL RESOURCES:

- https://course.ece.cmu.edu/~ece734/fall2019/lectures/9-deanonymization.pdf - Database Privacy: k-anonymity and
de-anonymization attacks... gets nice and technical!


-----------

### References

::: {#refs}
:::

