---
title: "Week 10: Hypothesis Testing and Alternatives"
subtitle: ""
author: "<large>Charlotte Hadley</large>"
format: 
  revealjs:
    theme: "css/lecture-styles.scss"
    slide-number: "c/t"
bibliography: "../bibtex-file.bib"
csl: "../nature.csl"
cache: true
self-contained: true
---

## Topics for today

```{r}
library(tidyverse)
library(gt)
library(readxl)
library(janitor)
```

-----------

# p-value notes

I'm dumping a bunch of useful stuff about p-values I found while writing Week 02 now.

## Twitter poll: same p-values different sizes

"If you have two studies with the *exact* same p-value, one with a small sample size and one with a large sample size, which would you find more convincing?"

- https://twitter.com/LucyStats/status/1029534591760195584?s=20&t=KE6HPh3zRy42IGvfu7Jp5g

And a GREAT follow-up article from the author https://livefreeordichotomize.com/2018/08/21/p-value-thoughts-a-twitter-follow-up/

Lucy D’Agostino McGowan follows up in 2022 with a great talk "What is the value of the p-value" (https://www.lucymcgowan.com/talk/north_carolina_translational_and_clinical_sciences_institute/) and the slides can be found here: https://docs.google.com/presentation/d/1W51xBJOG7C37vHLJuBR4WT6NCJXQN0Iah-NKk9VCLxg/edit#slide=id.p

Good tweet about what a p-value shows

```{r, eval=FALSE}
tweetrmd::tweet_embed("https://twitter.com/Andy_Bloch/status/1469396978261913601?s=20&t=g3jbJvlH_ri3Qhjb4dq7qA")
```

# The perils of exporatory data analysis

https://darrendahly.github.io/post/2017-02-03-exploratory/



-----------

### References

::: {#refs}
:::

